// ============================================================================
// /api/export/pdf — Investment Memo PDF Generator
// ============================================================================
// Generates a professional Goldman Sachs-style investment memorandum PDF
// from the full company data object. Uses jsPDF for server-side generation.
//
// POST /api/export/pdf
// Body: { company: <full company object> }
// Returns: PDF binary with Content-Type: application/pdf
// ============================================================================

import { NextResponse } from 'next/server';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { SCORE_WEIGHTS } from '@/lib/constants';

// ============ AUTHENTICATION ============
// Require a valid session — PDF exports contain sensitive DD data.
import { requireAuth } from '@/lib/security/session';

// ============ RATE LIMITING ============
// Prevent abuse — PDF generation is CPU-intensive.
import { rateLimitByApiRoute } from '@/lib/security/rateLimit';

// ============ COLOR CONSTANTS ============
const NAVY = [26, 35, 126];          // #1a237e — headers
const DARK_GRAY = [55, 65, 81];      // #374151 — body text
const LIGHT_GRAY = [229, 231, 235];  // #e5e7eb — table borders
const ACCENT_BLUE = [74, 125, 255];  // #4a7dff — highlights
const GREEN = [52, 211, 153];        // #34d399 — good scores
const AMBER = [245, 158, 11];        // #f59e0b — borderline
const RED = [239, 68, 68];           // #ef4444 — bad scores

// ============ HELPERS ============

// Get score color based on value
function getScoreColor(score) {
  const s = parseFloat(score) || 0;
  if (s >= 7) return GREEN;
  if (s >= 4) return AMBER;
  return RED;
}

// Safe field accessor — returns fallback if field is empty/undefined
function f(obj, key, fallback = '—') {
  const val = obj?.[key];
  if (val === undefined || val === null || val === '') return fallback;
  return String(val);
}

// Add a section header with navy background
function addSectionHeader(doc, title, y) {
  if (y > 250) {
    doc.addPage();
    y = 20;
  }
  doc.setFillColor(...NAVY);
  doc.rect(14, y, 182, 9, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.text(title.toUpperCase(), 18, y + 6.5);
  doc.setTextColor(...DARK_GRAY);
  return y + 14;
}

// Add a labeled field line
function addField(doc, label, value, y, x = 16) {
  if (y > 275) {
    doc.addPage();
    y = 20;
  }
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 140);
  doc.text(label, x, y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...DARK_GRAY);

  // Wrap long text
  const maxWidth = x > 110 ? 70 : (x > 16 ? 70 : 170);
  const lines = doc.splitTextToSize(String(value || '—'), maxWidth);
  doc.text(lines, x, y + 4);
  return y + 4 + (lines.length * 4);
}

// Add a two-column field pair
function addFieldPair(doc, label1, val1, label2, val2, y) {
  const y1 = addField(doc, label1, val1, y, 16);
  const y2 = addField(doc, label2, val2, y, 110);
  return Math.max(y1, y2) + 2;
}

// ============ PDF GENERATION ============
function generateMemo(company) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const companyName = company.overview?.companyName || company.overview?.name || company.name || 'Unnamed Company';
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // ============ PAGE 1: COVER ============
  doc.setFillColor(...NAVY);
  doc.rect(0, 0, 210, 297, 'F');

  // DueDrill logo text
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.text('DueDrill', 105, 40, { align: 'center' });

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(180, 190, 220);
  doc.text('AI-Powered Due Diligence Platform', 105, 48, { align: 'center' });

  // Divider line
  doc.setDrawColor(74, 125, 255);
  doc.setLineWidth(0.5);
  doc.line(60, 55, 150, 55);

  // Company name
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(28);
  doc.setTextColor(255, 255, 255);
  const nameLines = doc.splitTextToSize(companyName, 140);
  doc.text(nameLines, 105, 80, { align: 'center' });

  // Subtitle
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(14);
  doc.setTextColor(180, 190, 220);
  doc.text('INVESTMENT MEMORANDUM', 105, 100 + (nameLines.length - 1) * 12, { align: 'center' });

  // Date
  doc.setFontSize(11);
  doc.text(today, 105, 115 + (nameLines.length - 1) * 12, { align: 'center' });

  // Confidential notice
  doc.setFontSize(8);
  doc.setTextColor(200, 200, 220);
  doc.text('CONFIDENTIAL — FOR AUTHORIZED RECIPIENTS ONLY', 105, 260, { align: 'center' });
  doc.text('This document contains proprietary analysis generated by DueDrill.', 105, 266, { align: 'center' });

  // ============ PAGE 2: EXECUTIVE SUMMARY ============
  doc.addPage();
  let y = 20;

  y = addSectionHeader(doc, 'Executive Summary', y);

  const overview = company.overview || {};
  y = addField(doc, 'ONE-LINE SUMMARY', f(overview, 'oneLineSummary'), y);
  y += 2;
  y = addFieldPair(doc, 'STAGE', f(overview, 'stage'), 'SECTOR', f(overview, 'sector'), y);
  y = addFieldPair(doc, 'FOUNDED', f(overview, 'yearFounded'), 'HQ', `${f(overview, 'hqCity', '')} ${f(overview, 'hqCountry', '')}`.trim() || '—', y);
  y = addFieldPair(doc, 'EMPLOYEES', f(overview, 'employeeCount'), 'WEBSITE', f(overview, 'websiteUrl'), y);
  y += 2;
  y = addField(doc, 'ELEVATOR PITCH', f(overview, 'elevatorPitch'), y);

  // ============ TEAM ASSESSMENT ============
  y += 4;
  y = addSectionHeader(doc, 'Team Assessment', y);

  const team = company.team || {};
  y = addFieldPair(doc, 'CEO', f(team, 'ceoName'), 'CTO', f(team, 'ctoName'), y);
  y = addField(doc, 'CEO BACKGROUND', f(team, 'ceoBackground'), y);
  y = addField(doc, 'CTO BACKGROUND', f(team, 'ctoBackground'), y);
  y = addFieldPair(doc, 'TEAM SIZE', f(team, 'totalTeamSize'), 'ENGINEERING', f(team, 'engineeringTeamSize'), y);
  y = addFieldPair(doc, 'FOUNDER-MARKET FIT', f(team, 'founderMarketFit'), 'PREVIOUS EXITS', f(team, 'previousExits'), y);
  y = addField(doc, 'ADVISORS', f(team, 'advisors'), y);
  y = addField(doc, 'BOARD MEMBERS', f(team, 'boardMembers'), y);

  // ============ PRODUCT & TECHNOLOGY ============
  y += 4;
  y = addSectionHeader(doc, 'Product & Technology', y);

  const product = company.product || {};
  y = addField(doc, 'PRODUCT DESCRIPTION', f(product, 'productDescription'), y);
  y = addFieldPair(doc, 'DEVELOPMENT STAGE', f(product, 'developmentStage'), 'TECH STACK', f(product, 'techStack'), y);
  y = addField(doc, 'COMPETITIVE ADVANTAGE', f(product, 'competitiveAdvantage'), y);
  y = addField(doc, 'PRODUCT ROADMAP', f(product, 'productRoadmap'), y);

  // ============ MARKET ANALYSIS ============
  y += 4;
  y = addSectionHeader(doc, 'Market Analysis', y);

  const market = company.market || {};
  y = addFieldPair(doc, 'TAM', f(market, 'tam'), 'SAM', f(market, 'sam'), y);
  y = addFieldPair(doc, 'SOM', f(market, 'som'), 'MARKET GROWTH RATE', f(market, 'marketGrowthRate'), y);
  y = addField(doc, 'MARKET TIMING', f(market, 'marketTimingAssessment'), y);
  y = addField(doc, 'KEY TRENDS', f(market, 'keyMarketTrends'), y);

  // ============ TRACTION & METRICS ============
  y += 4;
  y = addSectionHeader(doc, 'Traction & Key Metrics', y);

  const traction = company.traction || {};
  y = addFieldPair(doc, 'MRR', f(traction, 'mrr'), 'ARR', f(traction, 'arr'), y);
  y = addFieldPair(doc, 'MoM GROWTH', f(traction, 'momGrowthRate'), 'PAYING CUSTOMERS', f(traction, 'payingCustomers'), y);
  y = addFieldPair(doc, 'NET RETENTION', f(traction, 'netRevenueRetention'), 'CHURN RATE', f(traction, 'monthlyChurnRate'), y);

  // ============ FINANCIAL OVERVIEW ============
  y += 4;
  y = addSectionHeader(doc, 'Financial Overview', y);

  const financial = company.financial || {};
  y = addFieldPair(doc, 'MONTHLY REVENUE', f(financial, 'monthlyRevenue'), 'BURN RATE', f(financial, 'monthlyBurnRate'), y);
  y = addFieldPair(doc, 'RUNWAY', f(financial, 'runway'), 'GROSS MARGIN', f(financial, 'grossMargin'), y);
  y = addFieldPair(doc, 'CAC', f(financial, 'cac'), 'LTV', f(financial, 'ltv'), y);

  // ============ COMPETITIVE LANDSCAPE ============
  y += 4;
  y = addSectionHeader(doc, 'Competitive Landscape', y);

  const competitive = company.competitive || {};
  y = addField(doc, 'KEY COMPETITORS', f(competitive, 'keyCompetitors'), y);
  y = addField(doc, 'COMPETITIVE MOAT', f(competitive, 'competitiveMoat'), y);
  y = addField(doc, 'DIFFERENTIATION', f(competitive, 'differentiation'), y);

  // ============ RISK ASSESSMENT ============
  y += 4;
  y = addSectionHeader(doc, 'Risk Assessment', y);

  const risks = company.risks || {};
  y = addField(doc, 'KEY RISKS', f(risks, 'keyRisks'), y);
  y = addField(doc, 'MITIGATIONS', f(risks, 'mitigationStrategies'), y);

  // ============ DEAL TERMS ============
  y += 4;
  y = addSectionHeader(doc, 'Deal Terms', y);

  const deal = company.deal || {};
  y = addFieldPair(doc, 'VALUATION', f(deal, 'preMoneyValuation'), 'ROUND SIZE', f(deal, 'roundSize'), y);
  y = addFieldPair(doc, 'INSTRUMENT', f(deal, 'instrumentType'), 'TOTAL RAISED', f(deal, 'totalRaised'), y);
  y = addField(doc, 'KEY TERMS', f(deal, 'keyTerms'), y);
  y = addField(doc, 'USE OF FUNDS', f(deal, 'useOfFunds'), y);

  // ============ SCORE SUMMARY TABLE ============
  doc.addPage();
  y = 20;
  y = addSectionHeader(doc, 'Due Diligence Score Summary', y);

  // Build the score table data
  const scoreRows = [];
  let weightedTotal = 0;
  let totalWeight = 0;

  // SCORE_WEIGHTS is an object keyed by section name, not an array.
  // Iterate with Object.entries to get [sectionKey, config] pairs.
  for (const [sectionKey, config] of Object.entries(SCORE_WEIGHTS)) {
    const sectionData = company[sectionKey] || {};
    const score = parseFloat(sectionData[config.field]) || 5;
    const weight = config.weight;
    const weighted = (score * weight).toFixed(2);
    weightedTotal += score * weight;
    totalWeight += weight;

    scoreRows.push([
      sectionKey.charAt(0).toUpperCase() + sectionKey.slice(1),
      score.toFixed(1),
      `${(weight * 100).toFixed(0)}%`,
      weighted,
    ]);
  }

  const overallScore = totalWeight > 0 ? (weightedTotal / totalWeight).toFixed(1) : '5.0';

  // Render the score table
  autoTable(doc, {
    startY: y,
    head: [['Category', 'Score', 'Weight', 'Weighted']],
    body: scoreRows,
    foot: [['OVERALL SCORE', overallScore, '100%', overallScore]],
    theme: 'grid',
    headStyles: {
      fillColor: NAVY,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 9,
    },
    footStyles: {
      fillColor: NAVY,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 10,
    },
    bodyStyles: {
      fontSize: 9,
      textColor: DARK_GRAY,
    },
    columnStyles: {
      0: { cellWidth: 50 },
      1: { cellWidth: 30, halign: 'center' },
      2: { cellWidth: 30, halign: 'center' },
      3: { cellWidth: 30, halign: 'center' },
    },
    margin: { left: 30, right: 30 },
    didParseCell: (data) => {
      // Color-code the score column
      if (data.section === 'body' && data.column.index === 1) {
        const score = parseFloat(data.cell.raw) || 0;
        data.cell.styles.textColor = getScoreColor(score);
        data.cell.styles.fontStyle = 'bold';
      }
    },
  });

  // Verdict
  const verdictY = doc.lastAutoTable.finalY + 10;
  const scoreNum = parseFloat(overallScore);
  let verdict = 'Fail';
  if (scoreNum >= 8) verdict = 'Strong Pass';
  else if (scoreNum >= 7) verdict = 'Pass';
  else if (scoreNum >= 5) verdict = 'Borderline';
  else if (scoreNum >= 3) verdict = 'Weak';

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.setTextColor(...getScoreColor(scoreNum));
  doc.text(`VERDICT: ${verdict} (${overallScore}/10)`, 105, verdictY, { align: 'center' });

  // ============ FOOTER ON ALL PAGES ============
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(160, 160, 180);
    doc.text(`Generated by DueDrill — ${today}`, 14, 290);
    doc.text(`Page ${i} of ${pageCount}`, 196, 290, { align: 'right' });

    // Top border line on all pages except cover
    if (i > 1) {
      doc.setDrawColor(...ACCENT_BLUE);
      doc.setLineWidth(0.3);
      doc.line(14, 14, 196, 14);
    }
  }

  return doc.output('arraybuffer');
}

// ============ POST HANDLER ============
export async function POST(request) {
  try {
    // ============ AUTH + RATE LIMIT ============
    const authResult = await requireAuth(request);
    if (authResult instanceof Response) return authResult;

    const { success: withinLimit, remaining, resetAt } = rateLimitByApiRoute(request);
    if (!withinLimit) {
      return NextResponse.json(
        {
          success: false,
          error: 'Too many requests. Please wait before trying again.',
          retryAfter: Math.ceil((resetAt.getTime() - Date.now()) / 1000),
        },
        {
          status: 429,
          headers: {
            'X-RateLimit-Remaining': '0',
            'Retry-After': '60',
          },
        }
      );
    }

    const body = await request.json();
    const { company } = body;

    if (!company) {
      return NextResponse.json(
        { success: false, error: 'Company data is required.' },
        { status: 400 }
      );
    }

    // Generate the PDF
    const pdfBuffer = generateMemo(company);

    // Return as downloadable PDF
    const companyName = company.overview?.companyName || company.overview?.name || company.name || 'company';
    const safeName = companyName.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase();

    return new Response(pdfBuffer, {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="DueDrill-Memo-${safeName}-${new Date().toISOString().slice(0, 10)}.pdf"`,
        'Cache-Control': 'no-store',
      },
    });
  } catch (err) {
    console.error('[PDF] Generation error:', err);
    return NextResponse.json(
      { success: false, error: `PDF generation failed: ${err.message}` },
      { status: 500 }
    );
  }
}
