'use client';

// ============================================================================
// components/ui/SuggestionsCard.js — Smart Suggestions Dashboard Widget
// ============================================================================
// Displays actionable next-step suggestions generated by lib/suggestions.js.
// Designed as a compact, collapsible card that fits into the DashboardView
// layout between the AI Research banner and the key metrics row.
//
// Features:
//   - Color-coded icons by suggestion type (missing-data, low-score, etc.)
//   - Priority-based coloring: high=red, medium=amber, low=blue
//   - Collapsible: shows top 3 by default, "Show more" expands to all 5
//   - Action button per suggestion navigates to the relevant tab
//   - Empty state when no suggestions exist ("Looking good!")
//
// Props:
//   suggestions — array of suggestion objects from generateSuggestions()
//     Each: { id, type, priority, title, description, actionTab, actionLabel }
//   onNavigate(tabId) — callback to switch the active tab in the main layout
//
// Dark theme: matches DueDrill's #1e2130 / #252836 / #2d3148 palette
// ============================================================================

import React, { useState, useCallback } from 'react';

// ============================================================================
// PRIORITY COLOR MAP
// ============================================================================
// Maps priority levels to hex colors for the DueDrill dark theme.
// high = red (urgent, needs immediate attention)
// medium = amber (important but not critical)
// low = blue (informational, nice-to-have)
const PRIORITY_COLORS = {
  high:   { text: '#ef4444', bg: 'rgba(239, 68, 68, 0.10)', border: 'rgba(239, 68, 68, 0.25)' },
  medium: { text: '#f59e0b', bg: 'rgba(245, 158, 11, 0.10)', border: 'rgba(245, 158, 11, 0.25)' },
  low:    { text: '#4a7dff', bg: 'rgba(74, 125, 255, 0.10)', border: 'rgba(74, 125, 255, 0.25)' },
};

// ============================================================================
// TYPE ICON MAP
// ============================================================================
// Each suggestion type gets a distinct icon so the user can quickly scan
// and understand what kind of action is needed without reading the text.
const TYPE_ICONS = {
  'missing-data': '📋',   // clipboard — data needs to be filled in
  'low-score':    '⚠️',   // warning — score indicates risk
  'stale-data':   '🕐',   // clock — data is outdated
  'next-step':    '➡️',   // arrow — advancement action
  'risk-alert':   '🔴',   // red circle — serious risk flag
};

// ============================================================================
// DEFAULT VISIBLE COUNT
// ============================================================================
// Show this many suggestions before the "Show more" toggle.
// 3 keeps the card compact while still showing the most critical items.
const DEFAULT_VISIBLE = 3;

// ============================================================================
// COMPONENT
// ============================================================================
export default function SuggestionsCard({ suggestions = [], onNavigate }) {
  // ============ EXPAND/COLLAPSE STATE ============
  // Controls whether we show all suggestions or just the top DEFAULT_VISIBLE.
  const [isExpanded, setIsExpanded] = useState(false);

  // Toggle expansion state
  const handleToggle = useCallback(() => {
    setIsExpanded((prev) => !prev);
  }, []);

  // Navigate to the action tab for a specific suggestion
  const handleAction = useCallback((actionTab) => {
    if (onNavigate && actionTab) {
      onNavigate(actionTab);
    }
  }, [onNavigate]);

  // ============ EMPTY STATE ============
  // When there are no suggestions, show a positive confirmation message.
  // This is important UX: the absence of suggestions IS information —
  // it means the DD is in good shape.
  if (!suggestions || suggestions.length === 0) {
    return (
      <div className="bg-[#1e2130] border border-[#2d3148] rounded-lg p-5">
        <div className="flex items-center gap-3">
          <span className="text-2xl">✅</span>
          <div>
            <h3 className="text-[#e8e9ed] text-sm font-bold">
              Looking good! No urgent actions needed.
            </h3>
            <p className="text-[#6b7084] text-xs mt-0.5">
              All sections are sufficiently complete and scores are within acceptable ranges.
            </p>
          </div>
        </div>
      </div>
    );
  }

  // ============ DETERMINE VISIBLE SUGGESTIONS ============
  // Show either the truncated list or the full list based on expansion state.
  const visibleSuggestions = isExpanded
    ? suggestions
    : suggestions.slice(0, DEFAULT_VISIBLE);

  const hasMore = suggestions.length > DEFAULT_VISIBLE;

  // ============ COUNT HIGH-PRIORITY ITEMS ============
  // Shown in the header badge to communicate urgency at a glance.
  const highPriorityCount = suggestions.filter((s) => s.priority === 'high').length;

  return (
    <div className="bg-[#1e2130] border border-[#2d3148] rounded-lg overflow-hidden">
      {/* ============ HEADER ============ */}
      {/* Card title with suggestion count badge */}
      <div className="px-5 py-3.5 border-b border-[#2d3148] flex items-center justify-between">
        <div className="flex items-center gap-2.5">
          <span className="text-base">💡</span>
          <h3 className="text-[#e8e9ed] text-sm font-bold">
            Smart Suggestions
          </h3>
          {/* Total count badge */}
          <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-[#252836] text-[#9ca0b0]">
            {suggestions.length}
          </span>
        </div>

        {/* High-priority count badge — only shown when there are high-priority items */}
        {highPriorityCount > 0 && (
          <span
            className="text-[10px] font-bold px-2 py-0.5 rounded-full"
            style={{
              backgroundColor: PRIORITY_COLORS.high.bg,
              color: PRIORITY_COLORS.high.text,
              border: `1px solid ${PRIORITY_COLORS.high.border}`,
            }}
          >
            {highPriorityCount} urgent
          </span>
        )}
      </div>

      {/* ============ SUGGESTIONS LIST ============ */}
      <div className="px-4 py-3 space-y-2">
        {visibleSuggestions.map((suggestion) => {
          const colors = PRIORITY_COLORS[suggestion.priority] || PRIORITY_COLORS.low;
          const icon = TYPE_ICONS[suggestion.type] || '📌';

          return (
            <div
              key={suggestion.id}
              className="flex items-start gap-3 px-3 py-2.5 rounded-md transition-colors duration-150"
              style={{
                backgroundColor: colors.bg,
                border: `1px solid ${colors.border}`,
              }}
            >
              {/* Type icon — sized to align with the text block */}
              <span className="text-sm mt-0.5 shrink-0">{icon}</span>

              {/* Text content: title (bold) + description */}
              <div className="flex-1 min-w-0">
                <p
                  className="text-xs font-bold leading-snug"
                  style={{ color: colors.text }}
                >
                  {suggestion.title}
                </p>
                <p className="text-[#9ca0b0] text-[11px] mt-0.5 leading-snug">
                  {suggestion.description}
                </p>
              </div>

              {/* Action button — navigates to the relevant tab */}
              <button
                onClick={() => handleAction(suggestion.actionTab)}
                className="shrink-0 text-[10px] font-semibold px-2.5 py-1 rounded-md transition-all duration-150 cursor-pointer whitespace-nowrap"
                style={{
                  backgroundColor: `${colors.text}15`,
                  color: colors.text,
                  border: `1px solid ${colors.border}`,
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.backgroundColor = `${colors.text}30`;
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.backgroundColor = `${colors.text}15`;
                }}
                title={suggestion.actionLabel}
              >
                {suggestion.actionLabel}
              </button>
            </div>
          );
        })}
      </div>

      {/* ============ SHOW MORE / SHOW LESS TOGGLE ============ */}
      {/* Only rendered when there are more suggestions than DEFAULT_VISIBLE */}
      {hasMore && (
        <div className="px-4 pb-3">
          <button
            onClick={handleToggle}
            className="w-full text-center text-[11px] font-medium text-[#4a7dff] hover:text-[#6b9aff] transition-colors duration-150 cursor-pointer py-1.5 rounded-md hover:bg-[#4a7dff]/5"
          >
            {isExpanded
              ? 'Show less'
              : `Show ${suggestions.length - DEFAULT_VISIBLE} more suggestion${suggestions.length - DEFAULT_VISIBLE > 1 ? 's' : ''}`
            }
          </button>
        </div>
      )}
    </div>
  );
}
